### ISSUE TITLE
想请教一下大神的媒体指数和咨询指数爬取

### ISSUE THREAD

**Issue by huangzhaor** [longxiaofei/spider-BaiduIndex#16]
[新建 Microsoft Word 文档.docx](https://github.com/longxiaofei/spider-BaiduIndex/files/4460633/Microsoft.Word.docx)
上面是代码
为什么会出现一下的错误呢

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/spider-BaiduIndex-master/new_spider_without_selenium/news_feed.py", line 7, in <module>
    for index in baidu_index.get_index():
  File "C:\Users\Administrator\Desktop\spider-BaiduIndex-master\new_spider_without_selenium\get_extended_index.py", line 68, in get_index
    for formated_data in self._format_data(encrypt_data):
  File "C:\Users\Administrator\Desktop\spider-BaiduIndex-master\new_spider_without_selenium\get_extended_index.py", line 131, in _format_data
    keyword = str(data['word'])
KeyError: 'word'

此外，如果我想爬取咨询指数，我将这句成这样，
baidu_index = BaiduIndex(keywords, '2016-1-01', '2020-4-09',type,'feed')

也是错误的。请问怎么修改呢？

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/spider-BaiduIndex-master/new_spider_without_selenium/news_feed.py", line 5, in <module>
    baidu_index = BaiduIndex(keywords, '2016-1-01', '2020-4-09', type,'feed')
  File "C:\Users\Administrator\Desktop\spider-BaiduIndex-master\new_spider_without_selenium\get_extended_index.py", line 42, in __init__
    self._pre_url = self.pre_url_dict[kind]
KeyError: <class 'type'>

**Comment by longxiaofei** [comment]
已修复。
