### ISSUE TITLE
今天在·使用的时候似乎开始有点bug？

### ISSUE THREAD

**Issue by huangzhaor** [longxiaofei/spider-BaiduIndex#18]
Traceback (most recent call last):
  File "E:\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1689, in <module>
    main()
  File "E:\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\PyCharm 2018.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Administrator/Desktop/spider-BaiduIndex-master/spider-BaiduIndex-master/new_spider_without_selenium/demo.py", line 6, in <module>
    for index in baidu_index.get_index():
  File "C:\Users\Administrator\Desktop\spider-BaiduIndex-master\spider-BaiduIndex-master\new_spider_without_selenium\get_index.py", line 58, in get_index
    keywords=params_data['keywords']
  File "C:\Users\Administrator\Desktop\spider-BaiduIndex-master\spider-BaiduIndex-master\new_spider_without_selenium\get_index.py", line 109, in _get_encrypt_datas
    uniqid = datas['data']['uniqid']
TypeError: string indices must be integers

**Comment by longxiaofei** [comment]
Duplicate of #17

**Comment by huangzhaor** [comment]
昨天改了还是有问题，但是今天就好了很奇怪。。

**Comment by huangzhaor** [comment]
我觉得这个bug似乎和时间也有关系，昨晚又出现了。早上就没有事情，可能是晚上有段时间在更新？很奇怪
