### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by pu1ssant** [longxiaofei/spider-BaiduIndex#29]
Traceback (most recent call last):
  File "/Users/xxx/Desktop/baidu/demo.py", line 28, in <module>
    for index in baidu_index.get_index():
  File "/Users/xxx/Desktop/baidu/baidu_index/baidu_index.py", line 51, in get_index
    encrypt_datas, uniqid = self._get_encrypt_datas(
  File "/Users/xxx/Desktop/baidu/baidu_index/baidu_index.py", line 88, in _get_encrypt_datas
    uniqid = datas['data']['uniqid']
TypeError: string indices must be integers

用大佬的demo.py跑了一下，但出现了如上报错。cookies是配置成功了的。

**Comment by longxiaofei** [comment]
代码和cookie发我邮箱吧。

**Comment by pu1ssant** [comment]
> 代码和cookie发我邮箱吧。

SORRY.在设置cookie时少复制了BDUSS=这部分，现在OK了>_<
