### ISSUE TITLE
BaiduIndex.get_index()报错

### ISSUE THREAD

**Issue by hepl-sys** [longxiaofei/spider-BaiduIndex#74]
Traceback (most recent call last):
  File "/Users/apple/Desktop/hepl/wonderlab/快手/百度指数.py", line 27, in <module>
    for index in baidu_index.get_index():
  File "/Users/apple/Library/Python/3.8/lib/python/site-packages/baidux/baidu_index.py", line 51, in get_index
    encrypt_datas, uniqid = self._get_encrypt_datas(
  File "/Users/apple/Library/Python/3.8/lib/python/site-packages/baidux/baidu_index.py", line 88, in _get_encrypt_datas
    **uniqid = datas['data']['uniqid']**
TypeError: **string indices must be integers**

**Comment by longxiaofei** [comment]
请使用最新版本的`qdata`
